-- Backfill author credits for newer saved games and library fallback templates.
-- Template IDs match their existing /api/library slugs.
insert into public.game_creator_attributions (game_kind, game_id, title, creator_name) values
  ('library', 'bug-barrage-2p', 'BUG BARRAGE', 'Zane Beeai'),
  ('library', 'candy-break', 'CANDY BREAK', 'Shayaan Azeem'),
  ('library', 'castle-blast', 'CASTLE BLAST', 'Sahiti Dasari'),
  ('library', 'frog-dash', 'FROG DASH', 'Tony Pan'),
  ('library', 'frog-dash-2p', 'FROG DASH', 'Zane Beeai'),
  ('library', 'goal-bonk', 'GOAL BONK', 'Shayaan Azeem'),
  ('library', 'heron-hop', 'HERON HOP', 'Sahiti Dasari'),
  ('library', 'ice-fish-2p', 'ICE FISH', 'Tony Pan'),
  ('library', 'icefish-dash', 'ICEFISH DASH', 'Zane Beeai'),
  ('library', 'lily-leap-2p', 'LILY LEAP', 'Shayaan Azeem'),
  ('library', 'neon-bumpers', 'NEON BUMPERS', 'Sahiti Dasari'),
  ('library', 'robo-bonk', 'ROBO BONK', 'Tony Pan'),
  ('library', 'robo-bonk-2p', 'ROBO BONK', 'Zane Beeai'),
  ('library', 'rooftop-rush', 'ROOFTOP RUSH', 'Shayaan Azeem'),
  ('library', 'sky-dash-2p', 'SKY DASH', 'Sahiti Dasari'),
  ('library', 'sky-kart', 'SKY KART', 'Tony Pan'),
  ('library', 'sky-raiders', 'SKY RAIDERS', 'Zane Beeai'),
  ('library', 'sky-sprint', 'SKY SPRINT', 'Shayaan Azeem'),
  ('library', 'star-cat', 'STAR CAT', 'Sahiti Dasari'),
  ('library', 'star-cat-2p', 'STAR CAT', 'Tony Pan'),
  ('library', 'template-breakout', 'BRICK BUST', 'Zane Beeai'),
  ('library', 'template-coop', 'SWARM', 'Shayaan Azeem'),
  ('library', 'template-dodge', 'SKY FALL', 'Sahiti Dasari'),
  ('library', 'template-flappy', 'FLAP', 'Tony Pan'),
  ('library', 'template-platformer', 'COIN HOP', 'Zane Beeai'),
  ('library', 'template-pong', 'PONG', 'Shayaan Azeem'),
  ('library', 'template-runner', 'DASH DOG', 'Sahiti Dasari'),
  ('library', 'template-shooter', 'STAR BLAST', 'Tony Pan'),
  ('library', 'template-snake', 'SNAKE', 'Zane Beeai'),
  ('library', 'template-versus', 'LASER DUEL', 'Shayaan Azeem');
