-- Manual product attribution for existing games, separate from badge identity
-- and the original catalog/source/asset authorship metadata.
create table public.game_creator_attributions (
  game_kind text not null check (game_kind in ('catalog', 'library')),
  game_id text not null,
  title text not null,
  creator_name text not null check (length(trim(creator_name)) > 0),
  attribution text not null default 'manual' check (attribution = 'manual'),
  assigned_at timestamptz not null default now(),
  primary key (game_kind, game_id)
);
create index game_creator_attributions_name_idx
  on public.game_creator_attributions (creator_name);
alter table public.game_creator_attributions enable row level security;
revoke all on public.game_creator_attributions from public, anon, authenticated;
grant select on public.game_creator_attributions to service_role;

insert into public.game_creator_attributions (game_kind, game_id, title, creator_name) values
  ('catalog', 'kart', 'COAST CIRCUIT', 'Zane Beeai'),
  ('catalog', 'fighter', 'MIDNIGHT DUEL', 'Shayaan Azeem'),
  ('catalog', 'sonic-speed-reference', 'SONIC: COAST DASH', 'Sahiti Dasari'),
  ('catalog', 'batman-atari-fighter-reference', 'BATMAN ATARI: ROOFTOP DUEL', 'Tony Pan'),
  ('catalog', 'spider-man-fighter-reference', 'SPIDER-MAN: ROOFTOP WEB DUEL', 'Zane Beeai'),
  ('catalog', 'dk-climber-reference', 'DONKEY KONG CLIMB', 'Shayaan Azeem'),
  ('catalog', 'pac-man-maze-reference', 'PAC-MAN MAZE', 'Sahiti Dasari'),
  ('catalog', 'pole-position-racer-reference', 'POLE POSITION CIRCUIT', 'Tony Pan'),
  ('catalog', 'speed-platformer', 'AZURE DASH', 'Zane Beeai'),
  ('catalog', 'bomber', 'BLAST PATROL', 'Shayaan Azeem'),
  ('catalog', 'climber', 'CRANE RESCUE', 'Sahiti Dasari'),
  ('catalog', 'maze', 'GOOSE GHOSTS', 'Tony Pan'),
  ('catalog', 'breakout', 'PRISM BREAK', 'Zane Beeai'),
  ('catalog', 'formation-shooter', 'PRISM SQUADRON', 'Shayaan Azeem'),
  ('catalog', 'crossing', 'RIVER RUN', 'Sahiti Dasari'),
  ('catalog', 'missile-defense', 'SKY SHIELD', 'Tony Pan'),
  ('catalog', 'falling-blocks', 'STACK CIRCUIT', 'Zane Beeai'),
  ('catalog', 'asteroids', 'VECTOR DRIFT', 'Daniel Ching'),
  ('catalog', 'pong', 'VOLT RALLY', 'Eddie Bian'),
  ('library', 'asteroid-blast', 'ASTEROID BLAST', 'Shayaan Azeem'),
  ('library', 'asteroid-dash', 'ASTEROID DASH', 'Sahiti Dasari'),
  ('library', 'bada-beat', 'BADA BEAT', 'Tony Pan'),
  ('library', 'banana-gotham', 'BANANA GOTHAM', 'Zane Beeai'),
  ('library', 'big-ball-break', 'BIG BALL BREAK', 'Shayaan Azeem'),
  ('library', 'big-ball-break-2', 'BIG BALL BREAK', 'Sahiti Dasari'),
  ('library', 'casper-climb', 'CASPER CLIMB', 'Tony Pan'),
  ('library', 'cat-catcher', 'CAT CATCHER', 'Zane Beeai'),
  ('library', 'cat-catcher-2', 'CAT CATCHER', 'Shayaan Azeem'),
  ('library', 'cat-dash', 'CAT DASH', 'Sahiti Dasari'),
  ('library', 'cat-dash-2', 'CAT DASH', 'Tony Pan'),
  ('library', 'cloud-drift', 'CLOUD DRIFT', 'Zane Beeai'),
  ('library', 'craft-dash', 'CRAFT DASH', 'Shayaan Azeem'),
  ('library', 'dc-duel', 'DC DUEL', 'Sahiti Dasari'),
  ('library', 'donkey-climb', 'DONKEY CLIMB', 'Tony Pan'),
  ('library', 'dragon-keep', 'DRAGON KEEP', 'Zane Beeai'),
  ('library', 'duel-byte', 'DUEL BYTE', 'Shayaan Azeem'),
  ('library', 'exam-escape', 'EXAM ESCAPE', 'Sahiti Dasari'),
  ('library', 'exam-escape-2', 'EXAM ESCAPE', 'Tony Pan'),
  ('library', 'fairy-pie-drop', 'FAIRY PIE DROP', 'Zane Beeai'),
  ('library', 'frogger-dash', 'FROGGER DASH', 'Shayaan Azeem'),
  ('library', 'frogger-rush', 'FROGGER RUSH', 'Sahiti Dasari'),
  ('library', 'ghost-maze', 'GHOST MAZE', 'Tony Pan'),
  ('library', 'goose-chase', 'GOOSE CHASE', 'Zane Beeai'),
  ('library', 'goose-kong', 'GOOSE KONG', 'Shayaan Azeem'),
  ('library', 'gotham-gadgets', 'GOTHAM GADGETS', 'Sahiti Dasari'),
  ('library', 'hard-mode', 'HARD MODE', 'Tony Pan'),
  ('library', 'hero-duel', 'HERO DUEL', 'Zane Beeai'),
  ('library', 'ice-fish-dash', 'ICE FISH DASH', 'Shayaan Azeem'),
  ('library', 'ice-fish-run', 'ICE FISH RUN', 'Sahiti Dasari'),
  ('library', 'jelly-sub', 'JELLY SUB', 'Tony Pan'),
  ('library', 'jelly-sub-2', 'JELLY SUB', 'Zane Beeai'),
  ('library', 'pac-mates', 'PAC-MATES', 'Shayaan Azeem'),
  ('library', 'pack-that', 'PACK THAT!', 'Sahiti Dasari'),
  ('library', 'pie-anvil', 'PIE ANVIL', 'Tony Pan'),
  ('library', 'pie-anvil-dash', 'PIE ANVIL DASH', 'Zane Beeai'),
  ('library', 'pixel-fight', 'PIXEL FIGHT', 'Shayaan Azeem'),
  ('library', 'pizza-invaders', 'PIZZA INVADERS', 'Sahiti Dasari'),
  ('library', 'pizza-invaders-2', 'PIZZA INVADERS', 'Tony Pan'),
  ('library', 'pizza-invaders-3', 'PIZZA INVADERS', 'Zane Beeai'),
  ('library', 'pollen-dash', 'POLLEN DASH', 'Shayaan Azeem'),
  ('library', 'salsa-taco', 'SALSA TACO', 'Sahiti Dasari'),
  ('library', 'seal-slide', 'SEAL SLIDE', 'Tony Pan'),
  ('library', 'sky-karts', 'SKY KARTS', 'Zane Beeai'),
  ('library', 'slime-spell', 'SLIME SPELL', 'Shayaan Azeem'),
  ('library', 'speed-pong', 'SPEED PONG', 'Sahiti Dasari'),
  ('library', 'speed-pong-2', 'SPEED PONG', 'Tony Pan'),
  ('library', 'spellstack', 'SPELLSTACK', 'Zane Beeai'),
  ('library', 'spike-dash', 'SPIKE DASH', 'Shayaan Azeem'),
  ('library', 'spike-dash-2', 'SPIKE DASH', 'Sahiti Dasari'),
  ('library', 'star-catch', 'STAR CATCH', 'Tony Pan'),
  ('library', 'star-zapper', 'STAR ZAPPER', 'Zane Beeai'),
  ('library', 'train-snake', 'TRAIN SNAKE', 'Shayaan Azeem'),
  ('library', 'train-snake-2', 'TRAIN SNAKE', 'Sahiti Dasari'),
  ('library', 'turbo-dash', 'TURBO DASH', 'Tony Pan'),
  ('library', 'twin-tug', 'TWIN TUG', 'Zane Beeai'),
  ('library', 'web-cowl', 'WEB & COWL', 'Shayaan Azeem');
